#!/bin/bash

USER_CLJ_DIR=/Users/mmcgrana/Clojure
SHARED_JARS_DIR=$USER_CLJ_DIR/jars

# Local src, test, and classes
CP=src/:test/:classes/

# Local jars
if [ -d jars ]; then
    for file in jars/*.jar; do
        CP=$CP:$file
    done
fi


# Global jars.
for file in $SHARED_JARS_DIR/*.jar; do
    CP=$CP:$file
done

if [ -z "$1" ]; then
    CP=$CP:$USER_CLJ_DIR
    java -cp $CP jline.ConsoleRunner clojure.main
else
    java -cp $CP clojure.main $@
fi