#!/bin/bash

USER_CLJ_DIR=/Users/mmcgrana/Clojure
SHARED_JARS_DIR=$USER_CLJ_DIR/jars

BREAK_CHARS="(){}[],^%$#@\"\";:''|\\"
COMPS=$USER_CLJ_DIR/completions

# Local src, test, and classes
CP=src/:test/:classes/

# Local jars
if [ -d jars ]; then
    for file in jars/*.jar; do
        CP=$CP:$file
    done
fi

# Global jars.
for file in $SHARED_JARS_DIR/*.jar; do
    CP=$CP:$file
done

CP=$CP:$USER_CLJ_DIR
if [ -z "$1" ]; then
    rlwrap --remember -c -b $BREAK_CHARS -f $COMPS java -cp $CP clojure.main -r
else
    rlwrap --remember -c -b $BREAK_CHARS -f $COMPS java -cp $CP clojure.main -i $1 -r
fi
