#!/bin/bash 

USER_CLJ_DIR=/Users/mmcgrana/Clojure
YOURKIT_DYLB="/Applications/YourKit.app/bin/mac/libyjpagent.jnilib"

if [ -z "$1" ]; then
  echo "Usage: cljp <script_file.clj>"
else
  java -server -agentpath:$YOURKIT_DYLB -Xmx2g -cp `cljcp` clojure.main $USER_CLJ_DIR/run.clj $@
fi
